version: '3.7'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    container_name: "polls_project"
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/app"
    ports:
      - "8003:8000"
    environment:
      - SECRET_KEY=django-insecure-g5!a8u5z+2htw#$x!_rojf6ro6v@sef^^v9jx$qli+mlm=@(!a
    depends_on:
      - redis
  celery:
    build: .
    command: "celery -A core worker -l INFO"
    volumes:
      - ".:/app"
    environment:
      - SECRET_KEY=django-insecure-g5!a8u5z+2htw#$x!_rojf6ro6v@sef^^v9jx$qli+mlm=@(!a
    depends_on:
      - redis
      - web