# Generated by Django 3.2.5 on 2021-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210802_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='answers',
            field=models.ManyToManyField(to='polls.Answer'),
        ),
    ]
