# Generated by Django 3.2.5 on 2021-08-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_testrunquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrunquestion',
            name='answers',
        ),
        migrations.AddField(
            model_name='testrunquestion',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.answer'),
        ),
    ]
