# Generated by Django 3.2.5 on 2021-08-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210805_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestrunQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('testrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.testrun')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
