# Generated by Django 3.2.5 on 2021-08-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210804_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestrunQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='polls.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('testrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.testrun')),
            ],
        ),
    ]
